include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: seeeduino_xiao_ble
    shield: totem_dongle rgbled_adapter
    snippet: studio-rpc-usb-uart        # TODO: remove i dont use zmk studio
    cmake-args: -DCONFIG_ZMK_STUDIO=y   # TODO: remove i dont use zmk studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
